SELECT * FROM PS_PTPPB_DATATYPE WHERE PTPPB_DATATYPE_ID LIKE 'CIB%'
SELECT * FROM PS_PTPPB_DATADISP WHERE PTPPB_DATATYPE_ID LIKE 'CIB%'


SELECT HTMLAREA FROM PS_PTPPB_PGLT_URL

SELECT * FROM PSMSGNODEDEFN
SELECT * FROM PSNODEURITEXT

SELECT * FROM PS_PTPPB_SYSVAR

SELECT * FROM PSQRYFIELD WHERE QRYNAME = 'PT_SEC_ACCESSLOG_USER' AND COLUMNNUM <> 0 ORDER BY COLUMNNUM;

SELECT * FROM PSQRYFIELD

SELECT * FROM PSQRYFIELDDEP

SELECT * FROM PSQRYHEAD WHERE QRYNAME = 'PT_OBJSEC_USER';

SELECT * FROM PS_PTPPB_PAGELET

SELECT * FROM PS_PTPPB_PARM_VALS WHERE PTPPB_PAGELET_ID LIKE 'C%'

SELECT * FROM PS_PTPPB_PGLT_PRMS WHERE PTPPB_PAGELET_ID = 'CIB';
PT_SEC_ACCESSLOG_USER
LOGINDTTM


SELECT * FROM PSMSGCATDEFN 
WHERE MESSAGE_SET_NBR = 219
AND MESSAGE_NBR = 518

SELECT * FROM PSMSGCATDEFN 
WHERE MESSAGE_TEXT LIKE '%Pagelet%'

SELECT * FROM psprsmdefn
WHERE PORTAL_OBJNAME = 'ADMN_CIBER_TEST_HMPG'
WHERE PORTAL_NAME = 'EMPLOYEE'

SELECT * FROM PSPRSMATTR
WHERE PORTAL_OBJNAME = 'ADMN_CIBER_TEST_HMPG'

SELECT * FROM PSPRSMATTRVAL
WHERE PORTAL_OBJNAME = 'ADMN_CIBER_TEST_HMPG'

SELECT * FROM PSPRSMSYSATTR
WHERE PORTAL_OBJNAME = 'ADMN_CIBER_TEST_HMPG'

SELECT * FROM PSPRSMSYSATTRVL
WHERE PORTAL_OBJNAME = 'ADMN_CIBER_TEST_HMPG'

SELECT PORTAL_NAME,
 PORTAL_OBJNAME AS CONTENT_REFERENCE,
 PORTAL_LABEL,
 PORTAL_URI_SEG1 AS MENU,
 PORTAL_URI_SEG2 AS COMPONENT,
 PORTAL_URI_SEG3 AS MARKET
FROM psprsmdefn
 WHERE PORTAL_NAME = 'EMPLOYEE'
   AND PORTAL_URI_SEG2 like 'CIB%'
   
   
   
SELECT * FROM PS_PTPPB_DISP_FRMT
SELECT * FROM PS_PTPPB_PAGE_PVW

SELECT * FROM PSPNLGROUP  WHERE PNLGRPNAME = 'PTPPB_WIZARD' AND MARKET = 'GBL'



UPDATE PSACCESSLOG SET LOGOUTDTTM = TO_DATE('2016/02/01 21:02:44', 'yyyy/mm/dd hh24:mi:ss')

SELECT * FROM PSACCESSLOG WHERE OPRID = 'VP1'
AND LOGINDTTM > TO_DATE('30-JAN-16', 'DD-MON-YY')
AND LOGINDTTM < TO_DATE('01-FEB-16', 'DD-MON-YY')

COMMIT;